// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type KeyInitParameters struct {

	// Model alias mappings.
	// +mapType=granular
	Aliases map[string]*string `json:"aliases,omitempty" tf:"aliases,omitempty"`

	// Allowed cache control values.
	AllowedCacheControls []*string `json:"allowedCacheControls,omitempty" tf:"allowed_cache_controls,omitempty"`

	// List of allowed passthrough routes.
	AllowedPassthroughRoutes []*string `json:"allowedPassthroughRoutes,omitempty" tf:"allowed_passthrough_routes,omitempty"`

	// List of allowed API routes.
	AllowedRoutes []*string `json:"allowedRoutes,omitempty" tf:"allowed_routes,omitempty"`

	// Whether the key is blocked.
	Blocked *bool `json:"blocked,omitempty" tf:"blocked,omitempty"`

	// Budget reset duration (e.g., '30d', '1h').
	BudgetDuration *string `json:"budgetDuration,omitempty" tf:"budget_duration,omitempty"`

	// Budget ID to associate with this key.
	BudgetID *string `json:"budgetId,omitempty" tf:"budget_id,omitempty"`

	// Key-specific configuration.
	// +mapType=granular
	Config map[string]*string `json:"config,omitempty" tf:"config,omitempty"`

	// Key validity duration.
	Duration *string `json:"duration,omitempty" tf:"duration,omitempty"`

	// List of enforced params for this key (params that must be present in requests).
	EnforcedParams []*string `json:"enforcedParams,omitempty" tf:"enforced_params,omitempty"`

	// Guardrails for the key.
	Guardrails []*string `json:"guardrails,omitempty" tf:"guardrails,omitempty"`

	// User-friendly alias for the key.
	KeyAlias *string `json:"keyAlias,omitempty" tf:"key_alias,omitempty"`

	// The API key value. If not specified, a key will be generated.
	KeySecretRef *v1.SecretKeySelector `json:"keySecretRef,omitempty" tf:"-"`

	// Maximum budget for this key.
	MaxBudget *float64 `json:"maxBudget,omitempty" tf:"max_budget,omitempty"`

	// Maximum parallel requests allowed.
	MaxParallelRequests *float64 `json:"maxParallelRequests,omitempty" tf:"max_parallel_requests,omitempty"`

	// Metadata for the key.
	// +mapType=granular
	Metadata map[string]*string `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// Per-model budget limits.
	// +mapType=granular
	ModelMaxBudget map[string]*float64 `json:"modelMaxBudget,omitempty" tf:"model_max_budget,omitempty"`

	// Per-model RPM limits.
	// +mapType=granular
	ModelRpmLimit map[string]*float64 `json:"modelRpmLimit,omitempty" tf:"model_rpm_limit,omitempty"`

	// Per-model TPM limits.
	// +mapType=granular
	ModelTpmLimit map[string]*float64 `json:"modelTpmLimit,omitempty" tf:"model_tpm_limit,omitempty"`

	// List of models this key can access.
	Models []*string `json:"models,omitempty" tf:"models,omitempty"`

	// Organization ID associated with this key.
	OrganizationID *string `json:"organizationId,omitempty" tf:"organization_id,omitempty"`

	// Key permissions.
	// +mapType=granular
	Permissions map[string]*string `json:"permissions,omitempty" tf:"permissions,omitempty"`

	// List of prompt IDs this key can access.
	Prompts []*string `json:"prompts,omitempty" tf:"prompts,omitempty"`

	// Requests per minute limit.
	RpmLimit *float64 `json:"rpmLimit,omitempty" tf:"rpm_limit,omitempty"`

	// Type of RPM limit: 'key' (default) or 'team'. If 'team', RPM is shared across all keys for the team.
	RpmLimitType *string `json:"rpmLimitType,omitempty" tf:"rpm_limit_type,omitempty"`

	// Service account ID for team-owned keys.
	ServiceAccountID *string `json:"serviceAccountId,omitempty" tf:"service_account_id,omitempty"`

	// Soft budget limit for warnings.
	SoftBudget *float64 `json:"softBudget,omitempty" tf:"soft_budget,omitempty"`

	// Tags for the key.
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// Team ID associated with this key.
	TeamID *string `json:"teamId,omitempty" tf:"team_id,omitempty"`

	// Tokens per minute limit.
	TpmLimit *float64 `json:"tpmLimit,omitempty" tf:"tpm_limit,omitempty"`

	// Type of TPM limit: 'key' (default) or 'team'. If 'team', TPM is shared across all keys for the team.
	TpmLimitType *string `json:"tpmLimitType,omitempty" tf:"tpm_limit_type,omitempty"`

	// User ID associated with this key.
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`
}

type KeyObservation struct {

	// Model alias mappings.
	// +mapType=granular
	Aliases map[string]*string `json:"aliases,omitempty" tf:"aliases,omitempty"`

	// Allowed cache control values.
	AllowedCacheControls []*string `json:"allowedCacheControls,omitempty" tf:"allowed_cache_controls,omitempty"`

	// List of allowed passthrough routes.
	AllowedPassthroughRoutes []*string `json:"allowedPassthroughRoutes,omitempty" tf:"allowed_passthrough_routes,omitempty"`

	// List of allowed API routes.
	AllowedRoutes []*string `json:"allowedRoutes,omitempty" tf:"allowed_routes,omitempty"`

	// Whether the key is blocked.
	Blocked *bool `json:"blocked,omitempty" tf:"blocked,omitempty"`

	// Budget reset duration (e.g., '30d', '1h').
	BudgetDuration *string `json:"budgetDuration,omitempty" tf:"budget_duration,omitempty"`

	// Budget ID to associate with this key.
	BudgetID *string `json:"budgetId,omitempty" tf:"budget_id,omitempty"`

	// Key-specific configuration.
	// +mapType=granular
	Config map[string]*string `json:"config,omitempty" tf:"config,omitempty"`

	// Key validity duration.
	Duration *string `json:"duration,omitempty" tf:"duration,omitempty"`

	// List of enforced params for this key (params that must be present in requests).
	EnforcedParams []*string `json:"enforcedParams,omitempty" tf:"enforced_params,omitempty"`

	// Guardrails for the key.
	Guardrails []*string `json:"guardrails,omitempty" tf:"guardrails,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// User-friendly alias for the key.
	KeyAlias *string `json:"keyAlias,omitempty" tf:"key_alias,omitempty"`

	// Maximum budget for this key.
	MaxBudget *float64 `json:"maxBudget,omitempty" tf:"max_budget,omitempty"`

	// Maximum parallel requests allowed.
	MaxParallelRequests *float64 `json:"maxParallelRequests,omitempty" tf:"max_parallel_requests,omitempty"`

	// Metadata for the key.
	// +mapType=granular
	Metadata map[string]*string `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// Per-model budget limits.
	// +mapType=granular
	ModelMaxBudget map[string]*float64 `json:"modelMaxBudget,omitempty" tf:"model_max_budget,omitempty"`

	// Per-model RPM limits.
	// +mapType=granular
	ModelRpmLimit map[string]*float64 `json:"modelRpmLimit,omitempty" tf:"model_rpm_limit,omitempty"`

	// Per-model TPM limits.
	// +mapType=granular
	ModelTpmLimit map[string]*float64 `json:"modelTpmLimit,omitempty" tf:"model_tpm_limit,omitempty"`

	// List of models this key can access.
	Models []*string `json:"models,omitempty" tf:"models,omitempty"`

	// Organization ID associated with this key.
	OrganizationID *string `json:"organizationId,omitempty" tf:"organization_id,omitempty"`

	// Key permissions.
	// +mapType=granular
	Permissions map[string]*string `json:"permissions,omitempty" tf:"permissions,omitempty"`

	// List of prompt IDs this key can access.
	Prompts []*string `json:"prompts,omitempty" tf:"prompts,omitempty"`

	// Requests per minute limit.
	RpmLimit *float64 `json:"rpmLimit,omitempty" tf:"rpm_limit,omitempty"`

	// Type of RPM limit: 'key' (default) or 'team'. If 'team', RPM is shared across all keys for the team.
	RpmLimitType *string `json:"rpmLimitType,omitempty" tf:"rpm_limit_type,omitempty"`

	// Service account ID for team-owned keys.
	ServiceAccountID *string `json:"serviceAccountId,omitempty" tf:"service_account_id,omitempty"`

	// Soft budget limit for warnings.
	SoftBudget *float64 `json:"softBudget,omitempty" tf:"soft_budget,omitempty"`

	// Amount spent by this key.
	Spend *float64 `json:"spend,omitempty" tf:"spend,omitempty"`

	// Tags for the key.
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// Team ID associated with this key.
	TeamID *string `json:"teamId,omitempty" tf:"team_id,omitempty"`

	// Tokens per minute limit.
	TpmLimit *float64 `json:"tpmLimit,omitempty" tf:"tpm_limit,omitempty"`

	// Type of TPM limit: 'key' (default) or 'team'. If 'team', TPM is shared across all keys for the team.
	TpmLimitType *string `json:"tpmLimitType,omitempty" tf:"tpm_limit_type,omitempty"`

	// User ID associated with this key.
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`
}

type KeyParameters struct {

	// Model alias mappings.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Aliases map[string]*string `json:"aliases,omitempty" tf:"aliases,omitempty"`

	// Allowed cache control values.
	// +kubebuilder:validation:Optional
	AllowedCacheControls []*string `json:"allowedCacheControls,omitempty" tf:"allowed_cache_controls,omitempty"`

	// List of allowed passthrough routes.
	// +kubebuilder:validation:Optional
	AllowedPassthroughRoutes []*string `json:"allowedPassthroughRoutes,omitempty" tf:"allowed_passthrough_routes,omitempty"`

	// List of allowed API routes.
	// +kubebuilder:validation:Optional
	AllowedRoutes []*string `json:"allowedRoutes,omitempty" tf:"allowed_routes,omitempty"`

	// Whether the key is blocked.
	// +kubebuilder:validation:Optional
	Blocked *bool `json:"blocked,omitempty" tf:"blocked,omitempty"`

	// Budget reset duration (e.g., '30d', '1h').
	// +kubebuilder:validation:Optional
	BudgetDuration *string `json:"budgetDuration,omitempty" tf:"budget_duration,omitempty"`

	// Budget ID to associate with this key.
	// +kubebuilder:validation:Optional
	BudgetID *string `json:"budgetId,omitempty" tf:"budget_id,omitempty"`

	// Key-specific configuration.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Config map[string]*string `json:"config,omitempty" tf:"config,omitempty"`

	// Key validity duration.
	// +kubebuilder:validation:Optional
	Duration *string `json:"duration,omitempty" tf:"duration,omitempty"`

	// List of enforced params for this key (params that must be present in requests).
	// +kubebuilder:validation:Optional
	EnforcedParams []*string `json:"enforcedParams,omitempty" tf:"enforced_params,omitempty"`

	// Guardrails for the key.
	// +kubebuilder:validation:Optional
	Guardrails []*string `json:"guardrails,omitempty" tf:"guardrails,omitempty"`

	// User-friendly alias for the key.
	// +kubebuilder:validation:Optional
	KeyAlias *string `json:"keyAlias,omitempty" tf:"key_alias,omitempty"`

	// The API key value. If not specified, a key will be generated.
	// +kubebuilder:validation:Optional
	KeySecretRef *v1.SecretKeySelector `json:"keySecretRef,omitempty" tf:"-"`

	// Maximum budget for this key.
	// +kubebuilder:validation:Optional
	MaxBudget *float64 `json:"maxBudget,omitempty" tf:"max_budget,omitempty"`

	// Maximum parallel requests allowed.
	// +kubebuilder:validation:Optional
	MaxParallelRequests *float64 `json:"maxParallelRequests,omitempty" tf:"max_parallel_requests,omitempty"`

	// Metadata for the key.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Metadata map[string]*string `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// Per-model budget limits.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	ModelMaxBudget map[string]*float64 `json:"modelMaxBudget,omitempty" tf:"model_max_budget,omitempty"`

	// Per-model RPM limits.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	ModelRpmLimit map[string]*float64 `json:"modelRpmLimit,omitempty" tf:"model_rpm_limit,omitempty"`

	// Per-model TPM limits.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	ModelTpmLimit map[string]*float64 `json:"modelTpmLimit,omitempty" tf:"model_tpm_limit,omitempty"`

	// List of models this key can access.
	// +kubebuilder:validation:Optional
	Models []*string `json:"models,omitempty" tf:"models,omitempty"`

	// Organization ID associated with this key.
	// +kubebuilder:validation:Optional
	OrganizationID *string `json:"organizationId,omitempty" tf:"organization_id,omitempty"`

	// Key permissions.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Permissions map[string]*string `json:"permissions,omitempty" tf:"permissions,omitempty"`

	// List of prompt IDs this key can access.
	// +kubebuilder:validation:Optional
	Prompts []*string `json:"prompts,omitempty" tf:"prompts,omitempty"`

	// Requests per minute limit.
	// +kubebuilder:validation:Optional
	RpmLimit *float64 `json:"rpmLimit,omitempty" tf:"rpm_limit,omitempty"`

	// Type of RPM limit: 'key' (default) or 'team'. If 'team', RPM is shared across all keys for the team.
	// +kubebuilder:validation:Optional
	RpmLimitType *string `json:"rpmLimitType,omitempty" tf:"rpm_limit_type,omitempty"`

	// Service account ID for team-owned keys.
	// +kubebuilder:validation:Optional
	ServiceAccountID *string `json:"serviceAccountId,omitempty" tf:"service_account_id,omitempty"`

	// Soft budget limit for warnings.
	// +kubebuilder:validation:Optional
	SoftBudget *float64 `json:"softBudget,omitempty" tf:"soft_budget,omitempty"`

	// Tags for the key.
	// +kubebuilder:validation:Optional
	Tags []*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// Team ID associated with this key.
	// +kubebuilder:validation:Optional
	TeamID *string `json:"teamId,omitempty" tf:"team_id,omitempty"`

	// Tokens per minute limit.
	// +kubebuilder:validation:Optional
	TpmLimit *float64 `json:"tpmLimit,omitempty" tf:"tpm_limit,omitempty"`

	// Type of TPM limit: 'key' (default) or 'team'. If 'team', TPM is shared across all keys for the team.
	// +kubebuilder:validation:Optional
	TpmLimitType *string `json:"tpmLimitType,omitempty" tf:"tpm_limit_type,omitempty"`

	// User ID associated with this key.
	// +kubebuilder:validation:Optional
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`
}

// KeySpec defines the desired state of Key
type KeySpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     KeyParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider KeyInitParameters `json:"initProvider,omitempty"`
}

// KeyStatus defines the observed state of Key.
type KeyStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        KeyObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Key is the Schema for the Keys API. Manages a LiteLLM API key. Keys are used to authenticate requests to the LiteLLM proxy and can be scoped to teams, models, and budgets.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,litellm}
type Key struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              KeySpec   `json:"spec"`
	Status            KeyStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// KeyList contains a list of Keys
type KeyList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Key `json:"items"`
}

// Repository type metadata.
var (
	Key_Kind             = "Key"
	Key_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Key_Kind}.String()
	Key_KindAPIVersion   = Key_Kind + "." + CRDGroupVersion.String()
	Key_GroupVersionKind = CRDGroupVersion.WithKind(Key_Kind)
)

func init() {
	SchemeBuilder.Register(&Key{}, &KeyList{})
}
